### ISSUE TITLE
Feedback from CodersX

### ISSUE THREAD

**Issue by LuongQuyTan1999** [minhquanghaiquan/clock-timezone#1]
- [ ]  Nên viết hướng dẫn setup môi trường ở README

- [ ] Rồi components, containers ....., cấu trúc thư mục cơ bản của ReactJs đâu rồi :((, mình nghĩ hiện tại bạn đang sử dụng Reactjs thì nên tập cấu trúc thư mục theo Reactjs, dù project có nhỏ cỡ nào thì cũng phải chia ra components.
![image](https://user-images.githubusercontent.com/53344335/85218171-d44b8300-b3c1-11ea-95ea-bb61c133bd42.png)

- [ ] Đã làm pet project thì nên deploy lên đâu đấy (firebase) chứ không nên để link codesandbox như thế này

- [ ] Mình nghĩ bạn nên tìm hiểu cách cấu trúc thư mục của Reactjs và sau đó viết lại project này và chia component cho nó.

**Comment by minhquanghaiquan** [comment]
> * [ ]   Nên viết hướng dẫn setup môi trường ở README
> * [ ]  Rồi components, containers ....., cấu trúc thư mục cơ bản của ReactJs đâu rồi :((, mình nghĩ hiện tại bạn đang sử dụng Reactjs thì nên tập cấu trúc thư mục theo Reactjs, dù project có nhỏ cỡ nào thì cũng phải chia ra components.
>   ![image](https://user-images.githubusercontent.com/53344335/85218171-d44b8300-b3c1-11ea-95ea-bb61c133bd42.png)
> * [ ]  Đã làm pet project thì nên deploy lên đâu đấy (firebase) chứ không nên để link codesandbox như thế này
> * [ ]  Mình nghĩ bạn nên tìm hiểu cách cấu trúc thư mục của Reactjs và sau đó viết lại project này và chia component cho nó.

Cảm ơn bạn!!

Mình đã chia thư mục ra cho project, sửa lại README và deploy lên trên heroku, mình có để link trong readme.

Mình giải thích tý, trong phần bài tập của coderx yêu cầu để link của codesandbox, nên ban đầu mình không deploy nhá!
